"""Where attachment bytes live.

Two implementations behind one protocol. S3 (MinIO locally, a bucket in a
deployment) is the real one. The filesystem store exists so the module runs on a
machine that has Postgres and Redis but no object storage — a common state on a
developer's laptop, and one where "documents cannot be uploaded" would take the
whole intake flow out of reach.

Which one is used is configuration, never detection. A deployment that has lost
its bucket should fail, not quietly start writing claim documents to a container
filesystem that disappears on the next deploy.
"""

from __future__ import annotations

import asyncio
import hashlib
from pathlib import Path
from typing import Protocol

from app.core.config import Settings, settings
from app.core.errors import ExternalServiceError
from app.core.logging import get_logger
from app.services.storage import ObjectStorage

logger = get_logger(__name__)


class DocumentStore(Protocol):
    """Content-addressed-ish blob storage for claim attachments."""

    async def put(self, key: str, content: bytes, *, content_type: str) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...


class ObjectStorageDocumentStore:
    """The deployed store: the service's S3 bucket."""

    def __init__(self, storage: ObjectStorage | None = None) -> None:
        self._storage = storage or ObjectStorage()

    async def put(self, key: str, content: bytes, *, content_type: str) -> None:
        await self._storage.put_object(key, content, content_type=content_type)

    async def get(self, key: str) -> bytes:
        return await self._storage.get_object(key)

    async def delete(self, key: str) -> None:
        await self._storage.delete_object(key)


class FilesystemDocumentStore:
    """A local directory, used when object storage is not part of the stack.

    Keys are treated as opaque paths and resolved against the root, with the
    resolution checked — a key is generated by this service, but a store that
    would happily write outside its root given the wrong one is a store waiting
    for the day something else generates a key.
    """

    def __init__(self, root: str | Path) -> None:
        self._root = Path(root).resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        candidate = (self._root / key).resolve()
        if not candidate.is_relative_to(self._root):
            raise ExternalServiceError("Refusing to resolve a document key outside the store.")
        return candidate

    async def put(self, key: str, content: bytes, *, content_type: str) -> None:
        del content_type  # The filesystem has nowhere to record it; the row does.
        path = self._path(key)
        await asyncio.to_thread(path.parent.mkdir, parents=True, exist_ok=True)
        await asyncio.to_thread(path.write_bytes, content)

    async def get(self, key: str) -> bytes:
        path = self._path(key)
        try:
            return await asyncio.to_thread(path.read_bytes)
        except FileNotFoundError as exc:
            raise ExternalServiceError("The stored document could not be found.") from exc

    async def delete(self, key: str) -> None:
        path = self._path(key)
        await asyncio.to_thread(path.unlink, True)


_store: DocumentStore | None = None


def get_document_store(config: Settings | None = None) -> DocumentStore:
    """The configured store, built once per process."""
    global _store
    if _store is None:
        config = config or settings
        if config.fnol.document_store == "filesystem":
            logger.info("document_store_filesystem", path=config.fnol.document_store_path)
            _store = FilesystemDocumentStore(config.fnol.document_store_path)
        else:
            logger.info("document_store_object_storage", bucket=config.s3.bucket)
            _store = ObjectStorageDocumentStore()
    return _store


def set_document_store(store: DocumentStore | None) -> None:
    """Override the process store. Used by tests."""
    global _store
    _store = store


#: The default top-level namespace. Claim attachments, which is what this module was
#: written for and still the overwhelming majority of what it stores.
DEFAULT_NAMESPACE = "fnol"


def storage_key(
    case_reference: str, checksum: str, filename: str, *, namespace: str = DEFAULT_NAMESPACE
) -> str:
    """A stable, collision-free key that leaks nothing.

    The owner reference makes the bucket browsable during an incident; the checksum
    makes re-uploading the same file idempotent; the hashed filename keeps the
    original name — which is user input — out of the key entirely.

    `namespace` is the top-level prefix, and it is a parameter rather than a constant
    because not everything this service stores is claim material. A carrier's policy
    wordings under `fnol/` would say those documents belong to a notice — which is the
    opposite of true, and they have a different retention and access story to match.
    Defaulted, so every existing caller keeps the key it already writes.
    """
    suffix = hashlib.sha256(filename.encode("utf-8")).hexdigest()[:8]
    return f"{namespace}/{case_reference}/{checksum[:16]}-{suffix}"
